import { z } from "zod";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "script", "config", "video", "audio", "frame"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);
const projectIdSchema = z.string().min(1).optional();
const projectCandidateSchema = z.object({ unitId: z.string().optional(), shotId: z.string().optional(), name: z.string().min(1), category: z.string().min(1), details: recordSchema.optional() });
const projectShotBoundarySchema = z.object({
    positions: z.array(z.string().min(1)).min(1).describe("至少一个主体的明确位置"),
    facing: z.array(z.string().min(1)).optional(),
    gaze: z.array(z.string().min(1)).optional(),
    hands: z.array(z.string().min(1)).optional(),
    heldProps: z.array(z.string().min(1)).optional(),
    visibleState: z.array(z.string().min(1)).optional(),
}).passthrough();
const projectShotMotionActionSchema = z.object({
    order: z.number().int().min(1),
    actor: z.string().min(1),
    trigger: z.string().optional(),
    action: z.string().min(1),
    pathOrContact: z.string().optional(),
    result: z.string().min(1),
}).passthrough();
const projectShotDefinitionSchema = z.object({
    schemaVersion: z.literal("mingwant.short-drama.shot/v1"),
    shotCode: z.string().min(1),
    sourceRefs: z.array(z.object({
        unitId: z.string().min(1),
        blockId: z.string().optional(),
        role: z.enum(["action", "dialogue", "sound", "text", "continuity"]),
        unitUpdatedAt: z.string().optional(),
    }).passthrough()).min(1),
    purpose: z.string().min(1),
    informationChange: z.string().min(1),
    assetBindings: z.array(z.object({
        assetVersionId: z.string().min(1),
        role: z.enum(["subject", "location", "prop", "wardrobe", "reference"]),
    }).passthrough()).describe("精确资产版本绑定；没有已确认资产时传空数组，不要省略"),
    startBoundary: projectShotBoundarySchema,
    endBoundary: projectShotBoundarySchema,
    motionSpec: z.object({
        startAnchor: z.string().min(1),
        orderedSubjectMotion: z.array(projectShotMotionActionSchema),
        performanceArc: z.string().min(1),
        camera: z.string().min(1),
        environmentAndAudio: z.array(z.string()).optional(),
        timingPlan: z.string().min(1),
        endReport: z.string().min(1),
    }).passthrough().optional(),
    imagePrompt: z.string().optional(),
    videoPrompt: z.string().optional(),
    negativePrompt: z.string().optional(),
}).passthrough().describe("完整的 mingwant.short-drama.shot/v1 镜头定义对象，不要传 JSON 字符串");
const projectShotSchema = z.object({
    id: z.string().optional().describe("更新既有镜头时传项目镜头 ID；新建时省略"),
    unitId: z.string().optional().describe("镜头所属分集或章节 ID"),
    title: z.string().min(1),
    description: z.string().optional(),
    definition: projectShotDefinitionSchema.optional(),
    position: z.number().int().min(0).optional(),
    durationMs: z.number().int().min(1).optional().describe("结构化镜头的毫秒时长，例如 8000；不要传 durationSeconds"),
    status: z.enum(["draft", "ready", "running", "review", "completed", "failed"]).optional(),
});

export const toolNames = [
    "canvas_get_state",
    "canvas_get_selection",
    "canvas_get_image_annotations",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_node",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_config_node",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "canvas_edit_image_annotation",
    "project_get_context",
    "project_list_units",
    "project_get_unit",
    "project_list_asset_versions",
    "project_create_unit",
    "project_update_unit",
    "project_extract_asset_candidates",
    "project_confirm_asset_candidate",
    "project_create_or_update_shots",
    "project_link_shot_asset",
    "project_start_workflow_step",
    "project_update_workflow_step",
    "project_link_asset",
    "project_upsert_asset_version",
    "project_register_task_output",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string(), fromHandleId: z.string().optional(), toHandleId: z.string().optional() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
    z.object({ type: z.literal("run_image_annotation"), annotationNodeId: z.string(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

export const toolInputSchemas = {
    canvas_get_state: z.object({}).passthrough(),
    canvas_get_selection: z.object({}).passthrough(),
    canvas_get_image_annotations: z.object({ nodeId: z.string().optional() }),
    canvas_export_snapshot: z.object({}).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema) }),
    canvas_create_node: z.object({ nodeType: nodeTypeSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), metadata: recordSchema.optional() }),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_config_node: z.object({ prompt: z.string().optional(), mode: generationModeSchema.optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string(), fromHandleId: z.string().optional(), toHandleId: z.string().optional() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }),
    canvas_edit_image_annotation: z.object({ annotationNodeId: z.string().min(1), prompt: z.string().optional() }),
    project_get_context: z.object({ projectId: projectIdSchema }),
    project_list_units: z.object({ projectId: projectIdSchema, kind: z.string().optional(), status: z.string().optional() }),
    project_get_unit: z.object({ projectId: projectIdSchema, unitId: z.string().min(1) }),
    project_list_asset_versions: z.object({ projectId: projectIdSchema, assetId: z.string().min(1) }),
    project_create_unit: z.object({ projectId: projectIdSchema, kind: z.enum(["chapter", "episode"]), title: z.string().min(1), sourceText: z.string().optional(), position: z.number().int().min(0).optional() }),
    project_update_unit: z.object({ projectId: projectIdSchema, unitId: z.string().min(1), title: z.string().min(1).optional(), sourceText: z.string(), status: z.enum(["draft", "ready", "completed"]).optional() }),
    project_extract_asset_candidates: z.object({ projectId: projectIdSchema, candidates: z.array(projectCandidateSchema).min(1).max(100) }),
    project_confirm_asset_candidate: z.object({ projectId: projectIdSchema, candidateId: z.string().min(1), assetId: z.string().optional() }),
    project_create_or_update_shots: z.object({ projectId: projectIdSchema, shots: z.array(projectShotSchema).min(1).max(100).describe("直接提交结构化对象；长分镜建议每批 3 到 5 镜") }),
    project_link_shot_asset: z.object({ projectId: projectIdSchema, shotId: z.string().min(1), assetVersionId: z.string().min(1), role: z.enum(["reference", "start_frame", "end_frame", "keyframe", "storyboard", "output"]) }),
    project_start_workflow_step: z.object({ projectId: projectIdSchema, stepId: z.string().min(1) }),
    project_update_workflow_step: z.object({ projectId: projectIdSchema, stepId: z.string().min(1), status: z.enum(["pending", "ready", "running", "review", "completed", "failed", "skipped"]), output: recordSchema, error: z.string().optional() }),
    project_link_asset: z.object({ projectId: projectIdSchema, assetId: z.string().min(1), category: z.string().min(1) }),
    project_upsert_asset_version: z.object({ projectId: projectIdSchema, assetId: z.string().min(1), prompt: z.string().optional(), definition: recordSchema.optional(), definitionJson: z.string().optional(), note: z.string().optional(), status: z.enum(["draft", "review", "confirmed"]).optional() }),
    project_register_task_output: z.object({ projectId: projectIdSchema, stepId: z.string().min(1), taskId: z.string().min(1), assetVersionId: z.string().optional(), resourceId: z.string().optional(), mediaType: z.string().optional(), role: z.enum(["reference", "start_frame", "end_frame", "keyframe", "storyboard", "output"]).optional(), metadataJson: z.string().optional(), outputJson: z.string().optional() }),
} satisfies Record<ToolName, z.AnyZodObject>;

export const toolDescriptions: Record<ToolName, string> = {
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_selection: "读取当前网页画布选中的节点。",
    canvas_get_image_annotations: "读取当前选区或指定节点关联的图片标注，并返回修改指令与带标记图片供视觉理解。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布。ops 支持 add_node、update_node、delete_node、delete_connections、connect_nodes、set_viewport、select_nodes、run_generation、run_image_annotation。",
    canvas_create_node: "创建任意类型节点：text、script、image、config、video、audio、frame。适合创建脚本、媒体占位、配置节点、背板或自定义 metadata 节点。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建文本节点，适合生成标题、段落、脚本、说明等内容块。",
    canvas_create_config_node: "创建生成配置节点，可指定 text/image/video/audio 模式和生成参数，可选择立即触发生成。",
    canvas_create_image_prompt_flow: "创建提示词文本节点和图片生成配置节点，并自动连线，可选择立即触发生图。",
    canvas_create_generation_flow: "创建通用生成流程：提示词文本节点、生成配置节点、参考节点连线，可用于文案、生图、视频或音频。",
    canvas_generate_text: "创建通用文本生成流程并立即触发生成。",
    canvas_generate_image: "创建通用图片生成流程并立即触发生成。",
    canvas_generate_video: "创建通用视频生成流程并立即通过画布已配置的视频模型触发生成。",
    canvas_generate_audio: "创建通用音频生成流程并立即触发生成。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "更新文本节点内容和标题。",
    canvas_move_nodes: "移动一个或多个节点，支持绝对坐标或 dx/dy 偏移。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定节点生成，通常用于配置节点或文本/图片/视频/音频节点。",
    canvas_edit_image_annotation: "使用标注节点保存的干净原图、修改指令和遮罩执行局部图片编辑；可用 prompt 覆盖原修改指令。",
    project_get_context: "读取当前制作项目的类型、项目单元摘要、画布、资产、镜头、候选和工作流事实。",
    project_list_units: "按类型或状态筛选当前制作项目的章节/项目单元摘要。",
    project_get_unit: "读取一个项目章节或分集的完整正文、逐字台词和当前修订信息。",
    project_list_asset_versions: "读取当前项目中一个资产的全部精确版本、结构化设定、提示词和修订信息。",
    project_create_unit: "在当前制作项目中新建章节或分集，并保存初始正文。",
    project_update_unit: "更新项目章节或分集的完整正文、标题和状态。",
    project_extract_asset_candidates: "将分镜识别出的角色、商品、品牌、授权文件、场景、服饰或道具需求登记为待确认资产候选。",
    project_confirm_asset_candidate: "确认一个资产候选，创建正式资产或关联已有个人资产。",
    project_create_or_update_shots: "创建或更新项目镜头业务数据；直接传结构化 definition 对象和毫秒 durationMs，不要先调用文本模型生成 JSON。长分镜每批 3 到 5 镜，失败时按返回的字段路径修正当前批次。",
    project_link_shot_asset: "将具体资产版本按首帧、尾帧或参考等用途关联到镜头。",
    project_start_workflow_step: "启动项目或章节制作流程中的一个步骤。",
    project_update_workflow_step: "保存工作流阶段候选、审查或交付结论，并更新步骤状态。",
    project_link_asset: "将个人资产引用到当前制作项目，不复制媒体文件。",
    project_upsert_asset_version: "为项目资产创建新的设定和提示词版本，保留历史版本；只有用户明确接受后才将 status 设为 confirmed。",
    project_register_task_output: "将成功生成任务挂到流程步骤，并登记到具体资产版本和资源表示。",
};
